#!/bin/bash

item_number=$1
shift

source "$HOME/tools/kkfunction.sh"

if [ -z "$item_number" ]; then
    kubecolor delete
    exit 1
fi

object_type=$(get_last_object_type)
item_name=$(get_item_name "$item_number")

read -p "Delete $object_type $item_name (y/N)? " -r REPLY
echo

if [[ $REPLY =~ ^[Yy]$ ]]; then
  set -x
  kubecolor delete "$object_type" "$item_name" $@
else
  echo "Keep it then!"
fi
