#!/bin/bash

source "$HOME/tools/kkfunction.sh"

OBJECT=$1

shift

switch_ns=""

ALL_NAMESPACES_OPTIONS=""
if [[ "$1" == "in" ]]; then
  if [[ "$2" == "all" ]]; then
    ALL_NAMESPACES_OPTIONS="--all-namespaces"
  else
    switch_ns=true
    namespace_substring="$2"
  fi
  shift 2
fi

if [[ "$1" == "on" ]]; then
  grep_and_switch_cluster "$2"
  shift 2
fi

if [[ "$1" == "in" ]]; then
  if [[ "$2" == "all" ]]; then
    ALL_NAMESPACES_OPTIONS="--all-namespaces"
  else
    switch_ns=true
    namespace_substring="$2"
  fi
  shift 2
fi

if [ -n "$switch_ns" ]; then
  grep_and_switch_namespace "$namespace_substring"
fi

grep_string=""
if [[ -n "$1" ]] && [[ "$1" != -* ]]; then
  grep_string="$1"
  shift
fi

case "$OBJECT" in
  "p") OBJECT="pod"
  ;;
  "d") OBJECT="deployment"
  ;;
  "svc") OBJECT="service"
  ;;
  "sa") OBJECT="ServiceAccount"
  ;;
  "a") OBJECT="applications"
  ;;
  "vs") OBJECT="VirtualServices"
  ;;
  "mc") OBJECT="ManagedCertificate"
  ;;
  "se") OBJECT="ServiceEntry"
  ;;
  "sec") OBJECT="secret"
  ;;
  "ss") OBJECT="StatefulSets"
  ;;
  "ds") OBJECT="DaemonSets"
  ;;
  "rs") OBJECT="ReplicaSets"
  ;;
  "rc") OBJECT="ReplicaControllers"
  ;;
  "j") OBJECT="job"
  ;;
  "cj") OBJECT="cronjob"
  ;;
  "gw") OBJECT="gateway"
  ;;
  "i") OBJECT="ingress"
  ;;
  "bc") OBJECT="BackendConfig"
  ;;
  "dr") OBJECT="DestinationRule"
  ;;
  "rb") OBJECT="rolebinding"
  ;;
  "r") OBJECT="roles"
  ;;
  "crb") OBJECT="clusterrolebinding"
  ;;
  "cr") OBJECT="clusterroles"
  ;;
esac

if [ -n "$grep_string" ]; then
  list_items "$OBJECT" "$ALL_NAMESPACES_OPTIONS" $@ | grep "$grep_string"
else
  list_items "$OBJECT" "$ALL_NAMESPACES_OPTIONS" $@
fi
