#!/bin/bash

item_number=$1
source "$HOME/tools/kkfunction.sh"
shift

object_type=$(get_last_object_type)
item_name=$(get_item_name "$item_number")

if [[ "$@" == *"--gcp"* ]]; then
  CURRENT_CONTEXT=$(kubectl config get-contexts | grep "*")
  NAMESPACE=$(echo "$CURRENT_CONTEXT" | awk '{print $5}')
  CLUSTER_PROJECT=$(echo "$CURRENT_CONTEXT" | awk '{print $3}' | awk -F'_' '{print $2}')

  open "https://console.cloud.google.com/logs/query;query=logName%3D%2528%22projects%2F${CLUSTER_PROJECT}%2Flogs%2Fstderr%22%20OR%20%22projects%2F${CLUSTER_PROJECT}%2Flogs%2Fstdout%22%2529%0Aresource.labels.namespace_name%3D%22${NAMESPACE}%22%0Aresource.labels.pod_name%3D%22${item_name}%22%0Aresource.labels.container_name!%3D%22istio-proxy%22;duration=PT30M?referrer=search&project=${CLUSTER_PROJECT}"
  exit 0
fi

TAIL_OPTION=""
if [[ "$@" == *"-f"* ]] || [[ "$@" == "--follow=true" ]]; then
  # By default, get only the last 50 line of logs if not streaming
  TAIL_OPTION="--tail=50"

  if [[ "$@" == *"--tail"* ]]; then
    TAIL_OPTION=""
  fi
fi

set -x
kubectl logs "$object_type"/"$item_name" $TAIL_OPTION $@
