#!/bin/bash

item_number=$1

source "$HOME/tools/kkfunction.sh"

if [ -z "$item_number" ]; then
    kubecolor rollout restart
    exit 1
fi

if [[ $item_number =~ ^[0-9]+$ ]]; then
  object_type=$(get_last_object_type)
  item_name=$(get_item_name "$item_number")
  set -x
  kubecolor rollout restart "$object_type"/"$item_name"
else
  set -x
  kubecolor rollout restart "$item_number"
fi
